### ISSUE TITLE
Add Enemy Behavior: Shooter

### ISSUE THREAD

**Issue by StephenHapp** [gmuGADIG/Princess-Starshine#22]

**Comment by PekkaBoi38** [comment]
Extra Notes: Distance between enemy and player is printed out in debug log. Upon submission, the enemy shoots a bullet when the player is within a distance of 4. Bullets are shot every 2 seconds and have a lifetime of 2 seconds. Bullets deal 20 damage to the player.
Concerns: Player keeps moving in the direction of bullet collision after a bullet hits them. It may be due to me not importing the right scripts.
